{% set name = "deepcs" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepcs-{{ version }}.tar.gz
  sha256: 5769ad2495a0d01babfd806f00b814b322dac9d2364607c0d10eb1628cb5ecf0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pytorch >=1.5.0
    - torchinfo >=0.0.9
    - torchvision >=0.6

test:
  imports:
    - deepcs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jeremyfix/deepcs
  summary: deepcs provides utilitary functions for the CentraleSupelec deeplearning lab works
  license: CECILL-C
  license_file: License_CeCILL-C.txt

extra:
  recipe-maintainers:
    - jeremyfix
