{% set name = "deepcs" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deepcs-{{ version }}.tar.gz
  sha256: 76d9d4015378eba81b8eaec28d818b7f71df8cd3fb248e6122a52f1f567489c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch >=1.5.0
    - torchinfo >=0.0.9
    - torchvision >=0.6

test:
  imports:
    - deepcs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jeremyfix/deepcs
  summary: deepcs provides utilitary functions for the CentraleSupelec deeplearning lab works
  license: CECILL-C
  license_file: License_CeCILL-C.txt

extra:
  recipe-maintainers:
    - jeremyfix
